version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    network_mode: host
    build: .
    env_file: .env
    depends_on:
      - db